"""Deterministic game recording and playback for YuGiOhEnvironment.

Records both agent and opponent actions in an interleaved list so that
a game can be replayed deterministically given the same setup (seed,
decks, agent_player).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from yugioh_env.models import YuGiOhAction
from yugioh_env.opponent import Opponent


class GameRecording:
    """Data model for a recorded game.

    Stores the setup metadata (seed, decks, agent_player) and an ordered
    list of action entries ``{"msg_type": int, "player": int,
    "action": int, "num_actions": int}``.
    """

    def __init__(self, setup: dict[str, Any]) -> None:
        self.setup = setup
        self.actions: list[dict[str, int]] = []

    def append(self, *, msg_type: int, player: int, action: int, num_actions: int) -> None:
        """Append an action entry to the recording."""
        self.actions.append(
            {
                "msg_type": msg_type,
                "player": player,
                "action": action,
                "num_actions": num_actions,
            }
        )

    def save(self, path: str | Path) -> None:
        """Serialize the recording to JSON."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            json.dump({"setup": self.setup, "actions": self.actions}, f, indent=2)

    @classmethod
    def load(cls, path: str | Path) -> GameRecording:
        """Deserialize a recording from JSON."""
        with open(path) as f:
            data = json.load(f)
        rec = cls(setup=data["setup"])
        rec.actions = data["actions"]
        return rec


class RecordingOpponent(Opponent):
    """Wraps any ``Opponent`` and records each action into a ``GameRecording``."""

    def __init__(self, inner: Opponent, recording: GameRecording) -> None:
        self._inner = inner
        self._recording = recording

    def select_action(self, msg: dict, num_actions: int) -> int:
        action = self._inner.select_action(msg, num_actions)
        self._recording.append(
            msg_type=msg.get("msg_type", 0),
            player=msg.get("player", 0),
            action=action,
            num_actions=num_actions,
        )
        return action

    @property
    def needs_observation(self) -> bool:
        return self._inner.needs_observation

    def set_observation(self, obs: dict) -> None:
        self._inner.set_observation(obs)

    def reseed(self, seed: int) -> None:
        self._inner.reseed(seed)


class RecordingEnvironment:
    """Wraps a ``YuGiOhEnvironment`` and records agent actions.

    Agent actions are recorded in ``step()``, opponent actions are recorded
    via a ``RecordingOpponent`` wrapper installed on the inner environment.
    Both streams appear interleaved in a single ``GameRecording.actions`` list.
    """

    def __init__(self, env: Any, opponent: Opponent) -> None:
        self._env = env
        self._opponent = opponent
        self._recording: GameRecording | None = None
        self._done = False

    def reset(self, **kwargs: Any):
        """Start a new episode and begin recording."""
        setup = {
            k: kwargs[k]
            for k in ("seed", "deck0", "deck1", "agent_player", "puzzle")
            if k in kwargs
        }
        self._recording = GameRecording(setup)
        self._done = False

        recording_opponent = RecordingOpponent(self._opponent, self._recording)
        self._env.set_opponent(recording_opponent)

        obs = self._env.reset(**kwargs)

        # Store the resolved agent_player (env resolves "random" internally)
        self._recording.setup["agent_player"] = self._env._agent_player

        return obs

    def step(self, action_index: int):
        """Execute an agent action, record it, and return the observation."""
        if self._done:
            return self._env.step(YuGiOhAction(action_index=action_index))

        # Record BEFORE stepping so the agent entry precedes any opponent
        # entries generated by _process_to_agent_choice inside env.step().
        msg_type = self._env._mapper.msg_type
        agent_player = self._env._agent_player
        num_actions = self._env.num_actions

        self._recording.append(
            msg_type=msg_type,
            player=agent_player,
            action=action_index,
            num_actions=num_actions,
        )

        obs = self._env.step(YuGiOhAction(action_index=action_index))
        if obs.done:
            self._done = True

        return obs

    def get_recording(self) -> GameRecording:
        """Return the current recording.

        Raises RuntimeError if no recording is active (reset not called).
        """
        if self._recording is None:
            raise RuntimeError("No active recording. Call reset() first.")
        return self._recording
